name: bot_flow_builder
description: Bot Flow Builder — mobile port
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
